#!/usr/bin/env python3
"""Compare escaped photon spectra: Kratos vs Python reference MCRT.

Self-contained: generates field/photon binaries and par file from CLI
arguments, runs Kratos, then runs the Python reference MCRT, and compares.

Usage:
  python3 compare_escaped.py [options]

Options:
  --tau0 TAU0        Line-centre half-slab tau0 (default: 1128.4)
  --a-voigt A        Voigt a parameter (default: 0.5)
  --n N              Number of photons (default: 5000)
  --n-scat-max NS    Max scatters: 0=zero, <0=unlimited, N>0=N (default: -1)
  --n-cell NX        Number of cells in x (default: 128)
  --seed SEED        RNG seed (default: 42)
  --no-kratos        Skip Kratos, use existing test_00000.bin
  --no-python        Skip Python reference
"""
import sys, os, argparse, subprocess, importlib;
from pathlib import Path;
from numpy import array, zeros, full, sqrt, pi, cos, sin, abs, asarray, \
                 median, histogram, arange, float32, float64, int32, \
                 random;

REPO = '/home/lilew/Seafile/seafile_sync/code/line_rt_pipeline';
sys.path.insert( 0, REPO );
sys.path.insert( 0, os.path.join( REPO, 'docs/reference_mcrt' ) );

from core.kratos_io import write_field_data, \
    write_photon_data, read_output;

m = importlib.import_module( 'mcrt' );

KRATOS_BIN = os.path.expanduser( \
    '~/apps/kratos_line_rt/bin/kratos' );
WORKDIR = os.path.expanduser( '~/scratch/line_rt' );
UNIT_L0 = 1.49597870691e13;
UNIT_T0 = 1.0;
L_SLAB = 1.49598e14;   # cm

PAR_TEMPLATE = """# Kratos Neufeld test - auto-generated by compare_escaped.py

[unit]
length  = %(unit_l0).6e
time    = %(unit_t0)s
density = 1.0

[mesh]
x_min = %(x_min).6f 0 0
x_max = %(x_max).6f 1 1
n_cell_global = %(nx)d 2 2

[cycle]
prefix_output = test
n_cycle_lim   = 0
t_lim         = %(t_lim)s
t_output_next = 1e32
dt_output     = 1e32
final_output  = 1

[particle]
n_step = %(n_step)d
n_scat = %(n_scat_par)d
output = 1
n_radiation = %(n_radiation)d

[line_rt]
field_file  = fields_neufeld.bin
photon_file = photons_neufeld.bin
ph_mode     = 1
b_sca       = %(b_sca_code).10e
const_abs   = 1
n_fld       = 1
num_rng     = 16381
a_voigt     = %(a_voigt)s

[device]
seed_rng = %(seed_rng)d

[boundary]
kinds = fre fre per per per per
"""


def gen_kratos_inputs( tau0, a_voigt, n_photon, n_cell, seed, \
                       n_scat_par, out_dir ):
    """Generate field binary, photon binary, and par file."""
    L_code = L_SLAB / UNIT_L0;
    dx_code = L_code / n_cell;
    half_code = L_code / 2.0;

    # mfp_i_sca_0 = 2*tau0 / L (half-slab convention: tau0 is
    # half-slab depth)
    mfp_i_sca_0_code = 2.0 * tau0 / L_SLAB * UNIT_L0;
    b_sca_code = 1.0e5 * UNIT_T0 / UNIT_L0;

    n_tot = n_cell * 2 * 2;
    shape3d = ( 2, 2, n_cell );  # (nz, ny, nx)
    fields = {
        'mfp_i_sca_0_' : full( shape3d, float32( mfp_i_sca_0_code ) ),
        'mfp_i_abs_0_' : zeros( shape3d, dtype = float32 ),
        'b_sca_'       : full( shape3d, float32( b_sca_code ) ),
        'vel_0_'       : zeros( shape3d, dtype = float32 ),
        'vel_1_'       : zeros( shape3d, dtype = float32 ),
        'vel_2_'       : zeros( shape3d, dtype = float32 ),
    };
    mesh = {
        'n_cell' : array( [ n_cell, 2, 2 ], dtype = int32 ),
        'x_min'  : array( [ -half_code, 0.0, 0.0 ], \
                          dtype = float32 ),
        'dx'     : array( [ dx_code, 0.5, 0.5 ], dtype = float32 ),
    };

    field_file = os.path.join( out_dir, 'fields_neufeld.bin' );
    write_field_data( field_file, fields, mesh );

    # Photon binary: isotropic midplane source
    photon_file = os.path.join( out_dir, 'photons_neufeld.bin' );
    rng = random.default_rng( seed );
    ph = zeros( ( n_photon, 9 ), dtype = float64 );
    ph[ :, 0 ] = 0.0;
    ph[ :, 1 ] = rng.uniform( 0.0, 1.0, n_photon );
    ph[ :, 2 ] = rng.uniform( 0.0, 1.0, n_photon );
    mu = rng.uniform( -1.0, 1.0, n_photon );
    phi = rng.uniform( 0.0, 2.0 * pi, n_photon );
    smu = sqrt( 1.0 - mu * mu );
    ph[ :, 3 ] = smu * cos( phi );
    ph[ :, 4 ] = smu * sin( phi );
    ph[ :, 5 ] = mu;
    ph[ :, 6 ] = 1.0 / n_photon;
    ph[ :, 7 ] = 0.0;
    ph[ :, 8 ] = 0.0;
    write_photon_data( photon_file, ph, n_col = 9 );

    # Par file
    n_sc_est = max( int( 2.857 * tau0 ), 1000 ) \
               if a_voigt > 1e-6 \
               else max( int( tau0 * tau0 ), 1000 );
    n_step = max( n_photon * n_sc_est * 3, 5000000 );

    par_path = os.path.join( out_dir, 'neufeld.par' );
    with open( par_path, 'w' ) as fp:
        fp.write( PAR_TEMPLATE % {
            'unit_l0'     : UNIT_L0,
            'unit_t0'     : UNIT_T0,
            'x_min'       : -half_code,
            'x_max'       : half_code,
            'nx'          : n_cell,
            't_lim'       : 600.0,
            'n_step'      : n_step,
            'n_scat_par'  : n_scat_par,
            'n_radiation' : n_photon,
            'b_sca_code'  : b_sca_code,
            'a_voigt'     : a_voigt,
            'seed_rng'    : seed,
        } );

    print( '  mfp_i_sca_0=%.4f (code), tau0_half=%.1f' \
           % ( mfp_i_sca_0_code, mfp_i_sca_0_code * half_code ) );
    print( '  n_step=%d, n_scat=%d, n_rad=%d' \
           % ( n_step, n_scat_par, n_photon ) );
    return par_path;


def run_kratos( par_path, out_dir, b_sca_cgs ):
    """Run Kratos and return escaped |x| array."""
    b_sca_code = b_sca_cgs * UNIT_T0 / UNIT_L0;
    result = subprocess.run(
        [ KRATOS_BIN, os.path.basename( par_path ) ],
        cwd = out_dir, capture_output = True, text = True, \
        timeout = 600,
    );
    if result.returncode != 0:
        print( 'Kratos FAILED. stderr: %s' % result.stderr[ -500 : ] );
        return None;
    # With t_output_next=1e32 + final_output=1, exactly one output
    # file: test_00000.bin
    out_file = Path( out_dir ) / 'test_00000.bin';
    if not out_file.exists( ):
        print( 'No Kratos output file: %s' % ( out_file, ) );
        return None;
    out = read_output( str( out_file ) );
    ph = out.get( 'photons', { } );
    vel = ph.get( 'vel' );
    if vel is None or len( vel ) == 0:
        print( 'No escaped photons in Kratos output.' );
        return None;
    x = abs( asarray( vel, dtype = float64 ) / b_sca_code );
    print( '  (read %s)' % out_file.name );
    print( '  Kratos: n=%d, med|x|=%.4f, mean|x|=%.4f, P(>3)=%.4f' \
           % ( len( x ), median( x ), x.mean( ), \
               ( x > 3 ).mean( ) ) );
    return x;


def run_python( tau0, a_voigt, n_photon, n_cell, seed, n_scat_max, \
                b_sca_cgs ):
    """Run Python reference MCRT and return escaped |x| array."""
    L = L_SLAB;
    mesh = {
        'n_cell' : array( [ n_cell, 2, 2 ], dtype = int32 ),
        'x_min'  : array( [ -L / 2, 0, 0 ], dtype = float64 ),
        'dx'     : array( [ L / n_cell, L * 0.1, L * 0.1 ], \
                          dtype = float64 ),
    };
    rng = random.default_rng( seed );
    ph = zeros( ( n_photon, 9 ) );
    ph[ :, 0 ] = 0.0;
    ph[ :, 1 ] = rng.uniform( 0, L * 0.1, n_photon );
    ph[ :, 2 ] = rng.uniform( 0, L * 0.1, n_photon );
    mu = rng.uniform( -1, 1, n_photon );
    phi = rng.uniform( 0, 2 * pi, n_photon );
    smu = sqrt( 1 - mu * mu );
    ph[ :, 3 ] = smu * cos( phi );
    ph[ :, 4 ] = smu * sin( phi );
    ph[ :, 5 ] = mu;
    ph[ :, 6 ] = 1.0 / n_photon;

    # mcrt.py treats n_scat_max=0 as unlimited; use -1 internally for 0.
    mcrt_ns = 0 if n_scat_max < 0 else n_scat_max;
    res = m.run_mcrt(
        mesh = mesh, photons = ph, b_sca = b_sca_cgs,
        mfp_i_sca_0 = 2.0 * tau0 / L, mfp_i_abs_0 = 0.0,
        vel = None, ph_mode = 1, a_voigt = a_voigt, seed = seed, \
        parallel = True, n_scat_max = mcrt_ns,
    );
    esc = array( res[ 'escaped' ] );
    x = abs( esc[ :, 0 ].astype( float64 ) / b_sca_cgs );
    nscat = array( res[ 'n_scat' ] );
    print( '  Python: n=%d, med|x|=%.4f, mean|x|=%.4f, P(>3)=%.4f, '
           '<N_sc>=%.0f' \
           % ( len( x ), median( x ), x.mean( ), ( x > 3 ).mean( ), \
               nscat.mean( ) ) );
    return x;


def print_comparison( xk, xp, n_scat_max ):
    if xk is not None and xp is not None:
        gap = ( median( xk ) / median( xp ) - 1 ) * 100;
        print( '\n  Gap: med|x| gap=%+.2f%%\n' % gap );

        bins = arange( 0, 10.5, 0.5 );
        hp, _ = histogram( xp, bins = bins );
        hk, _ = histogram( xk, bins = bins );
        bc = 0.5 * ( bins[ : -1 ] + bins[ 1: ] );
        print( '{x range: Kratos / Python}' );
        for c, k, p in zip( bc, hk, hp ):
            if p > 5 or k > 5:
                print( '  x=%4.1f  Kr=%5d  Py=%5d  K/P=%.3f' \
                       % ( c, k, p, k / max( p, 1 ) ) );
    elif xk is not None:
        print( '\n  Kratos only: med|x|=%.4f' % median( xk ) );
    elif xp is not None:
        print( '\n  Python only: med|x|=%.4f' % median( xp ) );

############################################################
#  Main

def main( ):
    p = argparse.ArgumentParser( \
        description = 'Compare Kratos vs Python MCRT escaped spectra.' );
    p.add_argument( '--tau0', type = float, default = 1128.4, \
                    help = 'Line-centre half-slab tau0' );
    p.add_argument( '--a-voigt', type = float, default = 0.5 );
    p.add_argument( '--n', type = int, default = 5000, \
                    dest = 'n_photon' );
    p.add_argument( '--n-scat-max', type = int, default = -1, \
                    help = '0=zero, <0=unlimited, N>0=N scatters' );
    p.add_argument( '--n-cell', type = int, default = 128 );
    p.add_argument( '--seed', type = int, default = 42 );
    p.add_argument( '--no-kratos', action = 'store_true', \
                    help = 'Skip Kratos, read existing test_00000.bin' );
    p.add_argument( '--no-python', action = 'store_true' );
    args = p.parse_args( );

    B_SCA_CGS = 1.0e5;
    n_scat_label = 'unlimited' if args.n_scat_max < 0 \
                   else str( args.n_scat_max );

    print( '=== compare_escaped.py ===' );
    print( '  tau0=%s, a=%s, n=%d, n_scat=%s, nx=%d' \
           % ( args.tau0, args.a_voigt, args.n_photon, \
               n_scat_label, args.n_cell ) );

    os.makedirs( WORKDIR, exist_ok = True );

    ############################################################
    #  Kratos

    xk = None;
    if not args.no_kratos:
        print( '\n--- Generating Kratos inputs ---' );
        n_scat_par = 1000000 if args.n_scat_max < 0 \
                     else max( args.n_scat_max, 1 );
        par_path = gen_kratos_inputs(
            args.tau0, args.a_voigt, args.n_photon, args.n_cell,
            args.seed, n_scat_par, WORKDIR );

        print( '--- Running Kratos ---' );
        # Remove stale output
        for f in Path( WORKDIR ).glob( 'test_0*.bin' ):
            f.unlink( );
        xk = run_kratos( par_path, WORKDIR, B_SCA_CGS );
    else:
        print( '\n--- Reading existing Kratos output ---' );
        out_files = sorted( Path( WORKDIR ).glob( 'test_0*.bin' ) );
        if out_files:
            out = read_output( str( out_files[ -1 ] ) );
            ph = out.get( 'photons', { } );
            vel = ph.get( 'vel' );
            if vel is not None and len( vel ) > 0:
                b_sca_code = B_SCA_CGS * UNIT_T0 / UNIT_L0;
                xk = abs( asarray( vel, dtype = float64 ) \
                          / b_sca_code );
                print( '  Kratos: n=%d, med|x|=%.4f' \
                       % ( len( xk ), median( xk ) ) );
            else:
                print( '  No escaped photons in output.' );
        else:
            print( '  No test_*.bin found.' );

    ############################################################
    #  Python

    xp = None;
    if not args.no_python:
        print( '\n--- Running Python reference MCRT ---' );
        xp = run_python( args.tau0, args.a_voigt, args.n_photon, \
                         args.n_cell, args.seed, args.n_scat_max, \
                         B_SCA_CGS );

    ############################################################
    #  Comparison

    print_comparison( xk, xp, args.n_scat_max );


if __name__ == '__main__':
    main( );
