#!/usr/bin/env python3
"""Generate voigt_table_data.h for the Kratos line_rt module.

Table: H(a, u) = voigt_profile(u, sigma=1/sqrt(2), gamma=a) = Re[w(u+ia)]/sqrt(2*pi),
the standard Hjerting function (NOT peak-normalized).  Grid: log-a in [A_MIN, A_MAX]
(NA points), u in [0, U_MAX] (NU points, uniform).  Stored row-major (u fastest),
matching the interp_t 2D setup in intg.h.

With the raw Hjerting convention the line-centre opacity is
    kappa(0) = mfp_i_sca_0 * H(a, 0)
which correctly accounts for Voigt broadening.  The previous peak-normalized
convention (H(a,u)/H(a,0)) gave kappa(0) = mfp_i_sca_0 for all a, over-estimating
the line-centre opacity by 1/H(a,0) (e.g. 1.62x for a=0.5).

NU=512 keeps the bilinear u-interpolation error below ~1% in the steep
core->wing transition (u ~ 2-3) for a ~ 0.01; at 64x512 the table is 128 KiB
and must go to DEVICE (global) memory, not constant memory.
"""

import numpy as np
from scipy.special import voigt_profile

NA = 64
NU = 512
A_MIN = 1e-5
A_MAX = 1e2
U_MIN = 0.0
U_MAX = 30.0

OUT = 'voigt_table_data.h'


def main():
    la = np.linspace(np.log(A_MIN), np.log(A_MAX), NA)
    u = np.linspace(U_MIN, U_MAX, NU)
    sig = 1.0 / np.sqrt(2.0)
    tab = np.empty((NA, NU))
    for i, a in enumerate(np.exp(la)):
        tab[i] = voigt_profile(u, sig, a) * np.sqrt(np.pi)

    with open(OUT, 'w') as fp:
        fp.write('// Voigt profile table — %dx%d, %dKB, scipy.special.voigt_profile\n'
                 '// Raw Hjerting H(a,u) (NOT peak-normalized). Grid: log-a [%g,%g], u [%g,%g]\n'
                 '// Generated by gen_voigt_table.py — do not edit by hand.\n\n'
                 % (NA, NU, NA * NU * 4 // 1024, A_MIN, A_MAX, U_MIN, U_MAX))
        fp.write('#pragma once\n\nnamespace prob {\n\n')
        fp.write('using float_t = type::float_t;\n\n')
        fp.write('constexpr int VOIGT_NA = %d;\n' % NA)
        fp.write('constexpr int VOIGT_NU = %d;\n' % NU)
        fp.write('constexpr float_t VOIGT_A_MIN = %.8e;\n' % A_MIN)
        fp.write('constexpr float_t VOIGT_A_MAX = %.8e;\n' % A_MAX)
        fp.write('constexpr float_t VOIGT_U_MIN = %.1f;\n' % U_MIN)
        fp.write('constexpr float_t VOIGT_U_MAX = %.1f;\n\n' % U_MAX)
        fp.write('const float_t voigt_table_data[%d] = {\n' % (NA * NU))
        for row in tab:
            fp.write('    ' + ', '.join('%.8e' % v for v in row) + ',\n')
        fp.write('};\n\n}\n')
    print(f'wrote {OUT}: {NA}x{NU} = {NA*NU*4//1024} KiB')


if __name__ == '__main__':
    main()
